//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuTungXeMay2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Idcontact { get; set; }
        public string tenNguoidung { get; set; }
        public string tenContact { get; set; }
        public string noidungContact { get; set; }
        public Nullable<int> sdt { get; set; }
    }
}
