//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuTungXeMay2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dathang
    {
        public Dathang()
        {
            this.Donhangs = new HashSet<Donhang>();
        }
    
        public int Iddonhang { get; set; }
        public Nullable<int> Idsp { get; set; }
        public Nullable<int> Idkhachhang { get; set; }
        public string Tensp { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<System.DateTime> Ngaymua { get; set; }
        public string Diachi { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string TenKh { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual ICollection<Donhang> Donhangs { get; set; }
    }
}
