//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuTungXeMay2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donhang
    {
        public int IdHoadon { get; set; }
        public Nullable<int> IdDonhang { get; set; }
        public string Chitiet { get; set; }
        public string Loaihinhthanhtoan { get; set; }
        public Nullable<int> Gia { get; set; }
        public string Email { get; set; }
        public string Diachi { get; set; }
        public Nullable<int> Tongtien { get; set; }
    
        public virtual Dathang Dathang { get; set; }
    }
}
